= Arquillian Testcontainers

Arquillian Testcontainers is a loadable extension for  https://testcontainers.com/[Testcontainers] support. This project
is not meant to provide an Arquillian adaptor via a Testcontainer, but rather compliment an Arquillian adaptor by
allowing Arquillian to manage a Testcontainer.

== Usage

To start using Arquillian Testcontainers add the following Maven dependency:

[source,xml]
----
<dependency>
    <groupId>org.arquillian.testcontainers</groupId>
    <artifactId>arquillian-testcontainers</artifactId>
    <version>${version.org.arquillian.testcontainers}</version>
    <scope>test</scope>
</dependency>
----

=== Using a Testcontainer

To use a Testcontainer within an Arquillian test you must annotate the type with `@TestcontainersRequired`. What this annotation
does is verify a Docker implementation is available. If a Docker implementation is not available, an exception is thrown.
By default, this is a `java.lang.AssertionError`. This can be overridden in the `@TestcontainersRequired(value=)` attribute. For
example in JUnit 5 to skip the test rather than throw an error you would use the `@TestcontainersRequired(TestAbortedException.class)`.
This would throw a `org.opentest4j.TestAbortedException` if a Docker implementation is not available and the test will
be skipped.

To inject a Testcontainer into your Arquillian test, use the `@Testcontainer` annotation.

[source,java]
----
@ExtendWith(ArquillianExtension.class)
@TestcontainersRequired(TestAbortedException.class)
@RunAsClient
public class SimpleContainerTest {

    @Testcontainer
    private static SimpleTestContainer container;

    @Deployment
    public static JavaArchive createDeployment() {
        return ShrinkWrap.create(JavaArchive.class)
                .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml");
    }

    @Test
    public void testContainerInjected() {
        Assertions.assertNotNull(container, "Expected the container to be injected.");
        Assertions.assertTrue(container.isRunning(), "Expected the container to not be running");
    }
}
----

The injected type must be an implementation of `org.testcontainers.containers.GenericContainer`. If you would like to
inject a `GenericContainer<?>`, you can use the `type` parameter in the `@Testcontainer` annotation to qualify the type:

[source,java]
----
@ExtendWith(ArquillianExtension.class)
@RunAsClient
@TestcontainersRequired(TestAbortedException.class)
public class TypeSpecifiedInjectionTest {

    @Deployment
    public static JavaArchive createDeployment() {
        return ShrinkWrap.create(JavaArchive.class)
                .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml");
    }

    @Testcontainer(type = WildFlyContainer.class)
    private GenericContainer<?> wildfly;

    @Testcontainer(type = SimpleTestContainer.class)
    private GenericContainer<?> container;

    @Test
    public void checkWildFly() {
        Assertions.assertNotNull(wildfly);
        Assertions.assertTrue(wildfly.isRunning());
    }

    @Test
    public void checkSimpleTestContainer() {
        Assertions.assertNotNull(container, "Expected the container to be injected.");
        Assertions.assertTrue(container.isRunning(), "Expected the container to be running");
    }
}
----

=== Container Lifecycle

By default, this extension manages the lifecycle of each Testcontainer per test class. The `@Testcontainer` annotation
accepts a `TestcontainerLifecycle` value to control when containers are started and stopped:

* `TestcontainerLifecycle.CLASS` (default) -- the container is started before each test class and stopped after it
  completes.
* `TestcontainerLifecycle.SUITE` -- the container is started once on first encounter and stopped when the test suite
  ends. The same container instance is shared across all test classes that request the same type with suite lifecycle.
  This is useful for expensive containers that do not need to be restarted between test classes.
* `TestcontainerLifecycle.MANUAL` -- the container is created and injected but never started or stopped by the
  framework. The user is responsible for managing the container lifecycle.

[source,java]
----
// Suite-scoped container shared across test classes
@Testcontainer(TestcontainerLifecycle.SUITE)
private KeycloakContainer keycloak;

// Class-scoped container (default behavior)
@Testcontainer
private SimpleTestContainer container;

// Manually managed container
@Testcontainer(TestcontainerLifecycle.MANUAL)
private SimpleTestContainer manualContainer;
----

== Helpers

Arquillian Testcontainers contains a helper for consuming log messages. The `LoggingConsumer` simply consumes the
containers output and logs it via a `java.util.logging.Logger`.

== WildFly Example

The following is an example of using a Testcontainer in WildFly with a `ServerSetupTask`.

[source,java]
----
@TestcontainersRequired
@ExtendWith(ArquillianExtension.class)
@RunAsClient
@ServerSetup(WildFlyTest.ContainerSetupTask.class)
public class WildFlyTest {
    @TestcontainersRequired
    @ReloadIfRequired
    public static class ContainerSetupTask implements ServerSetupTask {

        @Testcontainer
        private KeycloakContainer keycloak;

        @Override
        public final void setup(final ManagementClient managementClient, final String containerId) throws Exception {
            final var containerAddress = keycloak.getContainerAddress();
            // Do the Keycloak setup
        }

        @Override
        public final void tearDown(final ManagementClient managementClient, final String containerId) throws Exception {
        }
    }

    @Testcontainer
    private KeycloakContainer keycloak;

    @Deployment
    public static WebArchive createDeployment() {
        return ShrinkWrap.create(WebArchive.class)
                .addClasses(SecureEndpoint.class, SecureApplication.class)
                .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml");
    }

    @Test
    public void auth() throws Exception {
        final var response = makeRequest(keycloak.getContainerAddress(keycloak.getMappedPort(8080)));
        // Validate response
    }
}
----

== Releasing

Releasing the project requires permission to deploy to Maven Central see https://central.sonatype.org/publish/requirements/[Maven Central Release Requirements].
Once everything is setup, you simply need to run the `./release.sh` script. There are two required parameters:

1. `-r` or `--release` which is the version you want to release
2. `-d` or `--development` which is the next development version.

By default, the release version cannot contain `SNAPSHOT` and the development version, must container `SNAPSHOT`.

[source,bash]
.Example Command
----
./release -r 1.0.0.Final -d 1.0.1.Final-SNAPSHOT
----

=== Supported Arguments

|===
|Argument | Requires Value | Description

| `-d`, `--development`
| Yes
| The next version for the development cycle.

| `-f`, `--force`
| No
| Forces to allow a SNAPSHOT suffix in release version and not require one for the development version.

| `-h`, `--help`
| No
| Displays help

| `-p`, `--prerelease`
| No
| Indicates this is a prerelease and the GitHub release should be marked as such.

| `-r`, `--release`
| Yes
| The version to be released. Also used for the tag.

| `--dry-run`
| No
| Executes the release in as a dry-run. Nothing will be updated or pushed.

| `-v`, `--verbose`
| No
| Prints verbose output.

|===


Any additional arguments are considered arguments for the Maven command.
