# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Test

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - '.github/workflows/maven.yml'
      - '**/pom.xml'
      - 'src/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/maven.yml'
      - '**/pom.xml'
      - 'src/**'

# Only run the latest job
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Validate Formatting
        run: |
          mvn -B -ntp validate -Pformat-check
  build:
    needs: format-check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK's
        uses: actions/setup-java@v5
        with:
          java-version: |
            11
            17
            21
            25
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and Test on ${{ matrix.os }}
        run: mvn -B -V -ntp clean verify '-Djava11.home=${{env.JAVA_HOME_11_X64}}' '-Djava17.home=${{env.JAVA_HOME_17_X64}}' '-Djava21.home=${{env.JAVA_HOME_21_X64}}'
      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}
          path: '**/surefire-reports/*'
